{{- if .Values.backup_job.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-bucket-backup
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  BUCKET_URI: {{ .Values.backup_job.bucket_uri | b64enc }}
{{- end }}