{{- if .Values.restore_job.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-restore
  namespace:  {{ .Release.Namespace }}
  labels:
data:
  BUCKET_URI: {{ .Values.restore_job.bucket_uri | b64enc }}
{{- end }}